const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={
  view:'homeView', unit:localStorage.getItem('mausam_unit')||'C', mode:localStorage.getItem('mausam_mode')||'human', personality:localStorage.getItem('mausam_personality')||'friendly',
  location:JSON.parse(localStorage.getItem('mausam_location')||'null')||{name:'Jaipur',country:'India',latitude:26.9124,longitude:75.7873},
  interests:new Set(JSON.parse(localStorage.getItem('mausam_interests')||'["Health","Running","Travel","Family"]')),
  saved:JSON.parse(localStorage.getItem('mausam_saved')||'[]'), data:null
};
const interestOptions=['Health','Running','Cycling','Walking','Travel','Beach','Family','Gardening','Agriculture','Commuting','Photography','Outdoor events'];
const fmtTemp=v=>state.unit==='F'?Math.round(v*9/5+32):Math.round(v);
const temp=v=>`${fmtTemp(v)}°`;
const fmtTime=s=>{const d=new Date(s);return d.toLocaleTimeString([], {hour:'numeric'}).replace(':00','')};
const dayName=s=>new Date(s).toLocaleDateString([], {weekday:'short'});
const weatherIcon=c=>{if(c===0)return'☀️';if([1,2].includes(c))return'⛅';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if([51,53,55,56,57].includes(c))return'🌦️';if([61,63,65,80,81,82].includes(c))return'🌧️';if([71,73,75,77,85,86].includes(c))return'🌨️';if([95,96,99].includes(c))return'⛈️';return'🌤️'};
const weatherText=c=>{if(c===0)return'Clear';if([1,2].includes(c))return'Partly cloudy';if(c===3)return'Overcast';if([45,48].includes(c))return'Foggy';if([51,53,55,56,57].includes(c))return'Drizzle';if([61,63,65,80,81,82].includes(c))return'Rain';if([71,73,75,77,85,86].includes(c))return'Snow';if([95,96,99].includes(c))return'Thunderstorms';return'Cloudy'};
const rainPct=v=>Math.round(v||0);
function showToast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1900)}
function setView(id){state.view=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id==='placesView')renderPlaces();if(id==='insightsView')renderInsights();if(id==='settingsView')renderSettings();window.scrollTo({top:0,behavior:'smooth'});}
function openSheet(id){$(id).classList.remove('hidden')};function closeSheets(){$$('.sheet-backdrop').forEach(s=>s.classList.add('hidden'))}
async function fetchOpenMeteo(loc){
  const url=new URL('https://api.open-meteo.com/v1/forecast');
  url.searchParams.set('latitude',loc.latitude);url.searchParams.set('longitude',loc.longitude);url.searchParams.set('timezone','auto');
  url.searchParams.set('current','temperature_2m,relative_humidity_2m,apparent_temperature,is_day,precipitation,weather_code,pressure_msl,surface_pressure,wind_speed_10m,wind_direction_10m,uv_index');
  url.searchParams.set('hourly','temperature_2m,apparent_temperature,precipitation_probability,precipitation,weather_code,relative_humidity_2m,wind_speed_10m,uv_index,visibility');
  url.searchParams.set('daily','weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,sunrise,sunset,uv_index_max');url.searchParams.set('forecast_days','7');
  const r=await fetch(url); if(!r.ok) throw new Error('Weather request failed'); return r.json();
}
async function geocode(q){const u=new URL('https://geocoding-api.open-meteo.com/v1/search');u.searchParams.set('name',q);u.searchParams.set('count','8');u.searchParams.set('language','en');u.searchParams.set('format','json');const r=await fetch(u);if(!r.ok)throw new Error('Search failed');return (await r.json()).results||[]}
async function loadWeather(){
  setLoading(true); try{state.data=await fetchOpenMeteo(state.location);renderAll();localStorage.setItem('mausam_location',JSON.stringify(state.location));}catch(e){showToast('Could not refresh — showing demo data');state.data=demoData();renderAll();}finally{setLoading(false)}
}
function setLoading(on){$('#updateStamp').textContent=on?'Updating…':state.data?.current?`Updated ${new Date().toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`:'Demo data';}
function demoData(){const now=Date.now();const hs=Array.from({length:24},(_,i)=>({time:new Date(now+i*3600000).toISOString(),temperature_2m:27+Math.sin(i/3)*5,apparent_temperature:29+Math.sin(i/3)*5,precipitation_probability:[5,5,4,8,8,12,18,26,30,36,45,52,48,42,34,26,21,18,20,24,18,12,8,6][i],precipitation:0,weather_code:i>15?61:2,relative_humidity_2m:70+i%10,wind_speed_10m:10+i%7,uv_index:Math.max(0,8-Math.abs(12-i)),visibility:10000}));return{current:{temperature_2m:27,relative_humidity_2m:74,apparent_temperature:31,is_day:1,precipitation:0,weather_code:2,pressure_msl:1004,wind_speed_10m:16,wind_direction_10m:240,uv_index:8},hourly:{time:hs.map(x=>x.time),temperature_2m:hs.map(x=>x.temperature_2m),apparent_temperature:hs.map(x=>x.apparent_temperature),precipitation_probability:hs.map(x=>x.precipitation_probability),precipitation:hs.map(x=>x.precipitation),weather_code:hs.map(x=>x.weather_code),relative_humidity_2m:hs.map(x=>x.relative_humidity_2m),wind_speed_10m:hs.map(x=>x.wind_speed_10m),uv_index:hs.map(x=>x.uv_index),visibility:hs.map(x=>x.visibility)},daily:{time:Array.from({length:7},(_,i)=>new Date(now+i*86400000).toISOString().slice(0,10)),weather_code:[2,3,61,2,1,0,2],temperature_2m_max:[32,33,30,32,34,35,33],temperature_2m_min:[26,26,25,25,27,27,26],precipitation_probability_max:[20,12,66,24,8,6,18],precipitation_sum:[0,0.9,6.2,0,0,0,0.3],sunrise:Array(7).fill(new Date(now).toISOString()),sunset:Array(7).fill(new Date(now+12*3600000).toISOString()),uv_index_max:[8,8,6,8,9,9,8]}}}
function derive(){const c=state.data.current,h=state.data.hourly,d=state.data.daily;const uv=c.uv_index||0, hum=c.relative_humidity_2m||0, apparent=c.apparent_temperature||c.temperature_2m, rain=Math.max(...h.precipitation_probability.slice(0,12));const aqi=demoAQI(c.temperature_2m);const outdoor=clamp(Math.round(100 - Math.max(0,apparent-32)*7 - Math.max(0,uv-6)*6 - Math.max(0,hum-75)*.45 - rain*.35),28,97);const run=clamp(Math.round(outdoor + (apparent<30?8:apparent<33?0:-10) - Math.max(0,(h.wind_speed_10m[0]||0)-25)*.3),22,96);const comfort=clamp(Math.round(100-Math.abs(apparent-25)*5-Math.max(0,hum-65)*.3-Math.max(0,hum-25)*.05),25,95);const air=clamp(100-Math.max(0,aqi-50)*.38,18,97);return{uv,hum,apparent,rain,aqi,outdoor,run,comfort,air};}
const clamp=(n,a,b)=>Math.min(b,Math.max(a,n));function demoAQI(t){return clamp(Math.round(72+(t-25)*3),40,160)}
function humanMetric(name,v){if(state.mode==='precise')return v;const ranges={uv:v=>v>=8?'Very high':v>=6?'High':v>=3?'Moderate':'Low',hum:v=>v>75?'Very humid':v>55?'Comfortably humid':v<30?'Dry':'Balanced',wind:v=>v>30?'Strong':v>18?'Breezy':'Light wind',aqi:v=>v>=151?'Very unhealthy':v>=101?'Unhealthy for sensitive groups':v>=51?'Moderate':'Good',visibility:v=>v<2000?'Poor':v<5000?'Reduced': 'Clear'};return ranges[name]?ranges[name](v):String(v)}
function summary(d){const t=d.apparent,uv=d.uv,r=d.rain;let s=t>=34?'Hot and intense today. ':t>=30?'Warm and humid. ':t<=16?'Cool and crisp. ':'Comfortable conditions. ';if(uv>=8)s+=`UV gets very high${r>40?' and rain is building later.':'.'} `;else if(r>60)s+='Keep an umbrella close. ';else if(d.aqi>100)s+='Air quality is the bigger thing to watch. ';else s+='Your morning window looks best for outdoor plans. ';return s}
function renderAll(){if(!state.data)return;const d=derive(),c=state.data.current,h=state.data.hourly,daily=state.data.daily;$('#locationName').textContent=state.location.name;$('#locationSub').textContent=state.location.country||'Local forecast';$('#currentTemp').textContent=temp(c.temperature_2m);$('#currentCondition').textContent=weatherText(c.weather_code);$('#hiLo').textContent=`H ${temp(daily.temperature_2m_max[0])} · L ${temp(daily.temperature_2m_min[0])}`;$('#heroSummary').textContent=state.mode==='precise'?`Feels like ${temp(c.apparent_temperature)}. Humidity ${c.relative_humidity_2m}%. UV ${Math.round(c.uv_index||0)}.`:summary(d);$('#modeLabel').textContent=state.mode==='precise'?'Precise':'Human';renderRecommendations(d);renderScores(d);renderHourly(d);renderMetrics(d);renderDaily();setAtmosphere(c);setLoading(false);}
function renderRecommendations(d){const rec=[];if(state.interests.has('Running'))rec.push({i:'🏃',t:'Run',m:d.run>=80?'Excellent · before 10 AM':d.run>=60?'Moderate · go early':'Not ideal · try indoors',n:d.uv>=8?'Better before peak UV.':'Comfortable temperature and wind.'});if(state.interests.has('Health'))rec.push({i:'🫁',t:'Air quality',m:d.aqi>100?'Sensitive groups: caution':'Generally fine',n:`AQI ${d.aqi}. ${d.aqi>100?'Keep hard outdoor exercise brief.':'No major air-quality concern.'}`});if(state.interests.has('Travel')||state.interests.has('Commuting'))rec.push({i:'🚗',t:'Commute',m:d.rain>55?'Watch the rain':'Low weather risk',n:d.rain>55?'Rain probability rises soon.':'Visibility and wind look manageable.'});if(state.interests.has('Family'))rec.push({i:'🏡',t:'Family plans',m:d.uv>=8?'Best before noon':'Good for daytime',n:d.uv>=8?'The afternoon sun is too strong for long exposure.':'A comfortable window for errands and play.'});if(state.interests.has('Outdoor events'))rec.push({i:'✨',t:'Outdoor plans',m:d.outdoor>=80?'Excellent':'Conditional',n:`Overall outdoor score ${d.outdoor}/100.`});if(!rec.length)rec.push({i:'🌤️',t:'Outdoor plans',m:d.outdoor>=80?'Excellent':'Conditional',n:`Overall outdoor score ${d.outdoor}/100.`});$('#recommendations').innerHTML=rec.slice(0,6).map(x=>`<article class="rec-card"><div class="rec-icon">${x.i}</div><div class="rec-title">${x.t}</div><div class="rec-meta">${x.m}</div><div class="rec-note">${x.n}</div></article>`).join('')}
function renderScores(d){const arr=[['Outdoor',d.outdoor,'Temperature, UV, rain, wind'],['Running',d.run,'Heat stress + humidity'],['Comfort',d.comfort,'Feels-like conditions'],['Air',d.air,'Based on local air proxy']];$('#scoreGrid').innerHTML=arr.map(x=>`<div class="score"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="bar"><i style="width:${x[1]}%"></i></div><div class="reason">${x[2]}</div></div>`).join('')}
function renderHourly(d){const h=state.data.hourly;const n=Math.min(12,h.time.length);$('#hourlyRow').innerHTML=Array.from({length:n},(_,i)=>`<div class="hour ${i===0?'selected':''}"><div>${i===0?'Now':fmtTime(h.time[i])}</div><div class="hour-icon">${weatherIcon(h.weather_code[i])}</div><div class="hour-temp">${temp(h.temperature_2m[i])}</div><div class="hour-rain">${rainPct(h.precipitation_probability[i])}%</div></div>`).join('');drawChart();}
function drawChart(mode='temp'){const h=state.data.hourly,n=Math.min(12,h.time.length),vals=Array.from({length:n},(_,i)=>mode==='rain'?h.precipitation_probability[i]:h.temperature_2m[i]);const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min);const pts=vals.map((v,i)=>{const x=35+i*(830/(n-1));const y=26+(170-(v-min)/range*128);return[x,y]});const path=pts.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+','+p[1].toFixed(1)).join(' ');const area=path+' L '+pts[pts.length-1][0]+' 198 L '+pts[0][0]+' 198 Z';$('#hourlyChart').innerHTML=`<defs><linearGradient id="areaGradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#8fbfff" stop-opacity=".25"/><stop offset="1" stop-color="#8fbfff" stop-opacity="0"/></linearGradient></defs><line x1="0" y1="55" x2="900" y2="55" class="chart-grid-line"/><line x1="0" y1="105" x2="900" y2="105" class="chart-grid-line"/><line x1="0" y1="155" x2="900" y2="155" class="chart-grid-line"/><path class="chart-area" d="${area}"/><path class="chart-line" d="${path}"/>${pts.map(p=>`<circle class="chart-dot" cx="${p[0]}" cy="${p[1]}" r="4"/>`).join('')}`}
function renderMetrics(d){const c=state.data.current;const metrics=[['☀️','UV',state.mode==='precise'?Math.round(c.uv_index):humanMetric('uv',c.uv_index),c.uv_index>=8?'status-danger':c.uv_index>=6?'status-warn':'status-good',c.uv_index>=8?'Very high — protect exposed skin.':'Low to moderate exposure.'],['💧','Humidity',`${c.relative_humidity_2m}%`,'',humanMetric('hum',c.relative_humidity_2m)],['🌬️','Wind',`${Math.round(c.wind_speed_10m)} km/h`,'',humanMetric('wind',c.wind_speed_10m)],['🫁','Air quality',d.aqi,'status-warn',humanMetric('aqi',d.aqi)],['👁️','Visibility',`${Math.round((state.data.hourly.visibility?.[0]||10000)/1000*10)/10} km`,'',humanMetric('visibility',state.data.hourly.visibility?.[0]||10000)],['🧭','Pressure',`${Math.round(c.pressure_msl)} hPa`,'',c.pressure_msl>1010?'Above average pressure':'Low-to-normal pressure']];$('#metricGrid').innerHTML=metrics.map(m=>`<article class="metric"><div class="metric-top"><span class="metric-name">${m[1]}</span><span class="metric-icon">${m[0]}</span></div><div class="metric-value ${m[3]}">${m[2]}</div><div class="metric-desc">${state.personality==='playful'&&m[1]==='UV'&&c.uv_index>=8?'The sun has chosen violence today. ':''}${m[4]}</div></article>`).join('')}
function renderDaily(){const d=state.data.daily;$('#dailyList').innerHTML=d.time.map((day,i)=>`<div class="daily-row"><div class="daily-day">${i===0?'Today':dayName(day)}</div><div class="daily-state">${weatherIcon(d.weather_code[i])}</div><div class="rainpct">${rainPct(d.precipitation_probability_max[i])}%</div><div class="high">${temp(d.temperature_2m_max[i])}</div><div class="low">${temp(d.temperature_2m_min[i])}</div></div>`).join('')}
function setAtmosphere(c){const shell=$('#app-shell');shell.className='shell state-'+weatherText(c.weather_code).toLowerCase().replace(/[^a-z]+/g,'-');}
function renderPlaces(){let arr=state.saved.length?state.saved:[state.location];$('#savedPlaces').innerHTML=arr.map((p,i)=>`<div class="place" data-place="${i}"><div class="place-main"><div class="place-name">${p.name} ${i===0&&p.name===state.location.name?'':' '}</div><div class="place-sub">${p.country||'Saved destination'}</div></div><div class="place-temp">—</div><div class="place-fav">${i===0?'●':'○'}</div></div>`).join('');$$('#savedPlaces .place').forEach((el,idx)=>el.onclick=()=>{const p=arr[idx];state.location=p;loadWeather();setView('homeView');showToast(`Switched to ${p.name}`)})}
function renderInsights(){const d=derive(),arr=[['OUTDOOR','Is today good outside?',d.outdoor,'Best window depends on UV and rain.'],['RUNNING','Best time to run',d.run, d.run>80?'Go early while it is cooler.':'Consider an indoor session.'],['HEALTH','Sun + air',Math.round((d.air+d.uv*10)/2),d.uv>=8?'Sun protection is the priority.':'Conditions are manageable.'],['TRAVEL','Travel risk',clamp(100-Math.max(d.rain-30,0)-Math.max(0,state.data.current.wind_speed_10m-30),15,98),d.rain>60?'Allow extra time for weather.':'No major weather issue right now.']];$('#insightGrid').innerHTML=arr.map(x=>`<article class="insight-card"><div class="kicker">${x[0]}</div><h3>${x[1]}</h3><div class="insight-score">${x[2]}<span class="muted" style="font-size:14px"> / 100</span></div><div class="insight-copy">${x[3]}</div><span class="insight-chip">Explain this</span></article>`).join('')}
function renderSettings(){const host=$('#settingsCard');host.innerHTML=`<div class="setting-row"><div class="setting-copy"><h3>Presentation</h3><p>Switch between raw measurements and plain-language descriptions.</p></div><select class="select" id="modeSelect"><option value="human" ${state.mode==='human'?'selected':''}>Human</option><option value="precise" ${state.mode==='precise'?'selected':''}>Precise</option></select></div><div class="setting-row"><div class="setting-copy"><h3>Temperature unit</h3><p>Choose how temperatures appear throughout Mausam.</p></div><select class="select" id="unitSelect"><option value="C" ${state.unit==='C'?'selected':''}>°C</option><option value="F" ${state.unit==='F'?'selected':''}>°F</option></select></div><div class="setting-row"><div class="setting-copy"><h3>Personality</h3><p>How much personality should weather advice have?</p></div><select class="select" id="personalitySelect"><option value="calm">Calm</option><option value="friendly" ${state.personality==='friendly'?'selected':''}>Friendly</option><option value="playful" ${state.personality==='playful'?'selected':''}>Playful</option><option value="off">Off</option></select></div><div class="setting-row"><div class="setting-copy"><h3>Reduced motion</h3><p>Honor your device preference automatically in the full product.</p></div><button class="switch ${matchMedia('(prefers-reduced-motion: reduce)').matches?'on':''}" aria-label="Reduced motion"></button></div>`;
$('#modeSelect').onchange=e=>{state.mode=e.target.value;localStorage.setItem('mausam_mode',state.mode);renderAll();renderSettings()};$('#unitSelect').onchange=e=>{state.unit=e.target.value;localStorage.setItem('mausam_unit',state.unit);renderAll();renderSettings()};$('#personalitySelect').onchange=e=>{state.personality=e.target.value;localStorage.setItem('mausam_personality',state.personality);renderAll();renderSettings()};}
function renderInterestChips(){const wrap=$('#interestChips');wrap.innerHTML=interestOptions.map(x=>`<button class="chip ${state.interests.has(x)?'active':''}" data-interest="${x}">${x}</button>`).join('');$$('.chip').forEach(b=>b.onclick=()=>{b.classList.toggle('active');})}
async function searchPlaces(q,into='#searchResults'){if(!q.trim()){$(into).innerHTML='';return}try{const res=await geocode(q);$(into).innerHTML=res.map((r,i)=>`<div class="place" data-search-id="${i}"><div class="place-main"><div class="place-name">${r.name}</div><div class="place-sub">${[r.admin1,r.country].filter(Boolean).join(', ')}</div></div><div class="place-temp">›</div></div>`).join('')||'<div class="muted" style="padding:14px">No locations found.</div>';$$(`${into} .place`).forEach((el,i)=>{const r=res[i];el.onclick=()=>{state.location={name:r.name,country:r.country,latitude:r.latitude,longitude:r.longitude};if(!state.saved.some(x=>x.name===r.name&&x.latitude===r.latitude))state.saved=[state.location,...state.saved.filter(x=>x.name!==r.name)].slice(0,8);localStorage.setItem('mausam_saved',JSON.stringify(state.saved));closeSheets();loadWeather();setView('homeView');showToast(`Added ${r.name}`)}})}catch(e){$(into).innerHTML='<div class="muted" style="padding:14px">Search is temporarily unavailable.</div>'}}
$$('.nav-item').forEach(b=>b.onclick=()=>setView(b.dataset.view));
$('#refreshBtn').onclick=loadWeather;$('#locationBtn').onclick=()=>openSheet('#searchSheet');$('#searchBtn').onclick=()=>openSheet('#searchSheet');$('#settingsBtn').onclick=()=>{renderSettings();openSheet('#settingsSheet')};$('#personalizeBtn').onclick=()=>{renderInterestChips();openSheet('#personalizeSheet')};$('#explainScoresBtn').onclick=()=>showToast('Scores blend temperature, UV, humidity, rain, wind and air quality.');$('#detailsToggle').onclick=()=>{state.mode=state.mode==='human'?'precise':'human';localStorage.setItem('mausam_mode',state.mode);renderAll()};$('#modeBtn').onclick=()=>{$('#detailsToggle').click()};$('#saveInterestsBtn').onclick=()=>{state.interests=new Set($$('.chip.active').map(x=>x.dataset.interest));localStorage.setItem('mausam_interests',JSON.stringify([...state.interests]));closeSheets();renderAll();showToast('Personalization saved')};$$('[data-close-sheet]').forEach(b=>b.onclick=closeSheets);$$('.sheet-backdrop').forEach(s=>s.addEventListener('click',e=>{if(e.target===s)closeSheets()}));
let searchTimer;$('#globalSearch').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchPlaces(e.target.value),260)});$('#placeSearch').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>searchPlaces(e.target.value,'#savedPlaces'),260)});
$$('[data-hour-mode]').forEach(b=>b.onclick=()=>{$$('[data-hour-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');drawChart(b.dataset.hourMode)});
$$('[data-map-layer]').forEach(b=>b.onclick=()=>{$$('[data-map-layer]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#mapCaption').textContent={rain:'Light rain nearby · moving east',wind:'Winds are turning southerly',temp:`${temp(state.data?.current?.temperature_2m||27)} here · warmer to the west`}[b.dataset.mapLayer]});$('#centerMapBtn').onclick=()=>showToast('Centered on your location');
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
loadWeather();
